require "app/constants.rb"
require "app/game.rb"
require "app/flappy_dragon/flappy_dragon.rb"
require "app/pong/pong.rb"
require "app/bullet_hell/bullet_hell.rb"
require "app/home.rb"
require "app/tick.rb"
